spring.application.name=webprogramming
server.port=8090

## DATABASE CONFIG ##
# URL за връзка с H2 база данни, записана във файл
spring.datasource.url=jdbc:h2:file:./db/delivery_system_db
# JDBC драйвер за H2 базата данни
spring.datasource.driver-class-name=org.h2.Driver
# Потребителско име за достъп до базата данни
spring.datasource.username=root
# Парола за достъп до базата данни
spring.datasource.password=

## H2 CONFIG ##
# Активира H2 уеб конзолата
spring.h2.console.enabled=true
# URL път до H2 конзолата
spring.h2.console.path=/h2-console

# Винаги изпълнява SQL скриптовете при стартиране
spring.sql.init.mode=always

## JPA CONFIG ##
# Създава таблиците при старт и ги изтрива при спиране
spring.jpa.hibernate.ddl-auto=create-drop
# Показва SQL заявките в конзолата
spring.jpa.show-sql=true
# Изчаква инициализацията на базата преди изпълнение на JPA
spring.jpa.defer-datasource-initialization=true