-- Този файл ще бъде изпълнен от Spring при стартиране на приложението
-- служи за създаване на таблиците за нашето приложение
-- DDL

DROP TABLE DELIVERY;
DROP TABLE COURIER;
DROP TABLE CUSTOMER;
DROP TABLE WAREHOUSE;

CREATE TABLE IF NOT EXISTS COURIER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    AVAILABLE BOOLEAN,
    CITY VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(100),
    CITY VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS WAREHOUSE (
     ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     CITY VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS DELIVERY (
     ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     CREATED_AT TIMESTAMP NOT NULL,
     CUSTOMER_ID BIGINT NOT NULL,
     COURIER_ID BIGINT,
     WAREHOUSE_ID BIGINT NOT NULL,
     DELIVERED_AT TIMESTAMP,
     DELIVERY_STATUS VARCHAR(100) NOT NULL,
     ESTIMATED_ARRIVAL_AT TIMESTAMP NOT NULL,

    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    CONSTRAINT FK_COURIER FOREIGN KEY (COURIER_ID) REFERENCES COURIER(ID),
    CONSTRAINT FK_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(ID)
);